name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer install
        run: composer install

      - name: Run Tests
        run: composer test
        
      - name: Run codestyle checks
        run: composer codestyle-check
