name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Composer install
        run: composer install
        
      - name: Test
        run: ls -la tests/data/

      - name: Run Tests
        run: composer test